# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flVKNoBv6QTeI4HkzFROrgO7NaCOvoZL
"""

from flask import Flask, request, abort
import os
from linebot.v3 import WebhookHandler
from linebot.v3.exceptions import InvalidSignatureError
from linebot.v3.webhooks import MessageEvent, TextMessageContent
from linebot.v3.messaging import (
    Configuration, ApiClient, MessagingApi, MessagingApiBlob,
    RichMenuSize, RichMenuRequest, RichMenuArea, RichMenuBounds,
    MessageAction, URIAction, DatetimePickerAction
)



app = Flask(__name__)

configuration = Configuration(access_token=os.getenv('LINE_Channel_access_token'))

with ApiClient(configuration) as api_client:
    line_bot_api = MessagingApi(api_client)
    line_bot_blob_api = MessagingApiBlob(api_client)
    # 建立 rich menu 請求
    rich_menu_request = RichMenuRequest(
        size=RichMenuSize(width=800, height=270),
        selected=False,
        name='My Rich Menu',
        chatBarText='開啟選單',
        areas=[
            RichMenuArea(
                bounds=RichMenuBounds(x=0, y=0, width=266, height=270),
                action=URIAction(label='查看詳情', uri='https://zh.wikipedia.org/zh-tw/%E5%BC%B7%E9%A2%A8%E5%90%B9%E6%8B%82')
            ),
            RichMenuArea(
                bounds=RichMenuBounds(x=266, y=0, width=267, height=270),
                action=MessageAction(text="推薦熱血運動番強風吹拂")
            ),
            RichMenuArea(
                bounds=RichMenuBounds(x=533, y=0, width=267, height=270),
                action=DatetimePickerAction(label="選擇時間", data="action=richmenu", mode="datetime")
            )
        ]
    )
    # 創建 Rich Menu
    rich_menu_id = line_bot_api.create_rich_menu(rich_menu_request=rich_menu_request).rich_menu_id
    print(f"Rich menu created with ID: {rich_menu_id}")
    # 上傳選單背景圖
    with open('https://cdn.pixabay.com/photo/2025/05/18/14/05/congratulations-9607355_1280.png', 'rb') as image:
        line_bot_blob_api.set_rich_menu_image(
            rich_menu_id=rich_menu_id,
            body=bytearray(image.read()),
            _headers={'Content-Type': 'image/png'}
        )
    # 將 Rich Menu 設為預設
    line_bot_api.set_default_rich_menu(rich_menu_id)



if __name__ == "__main__":
    app.run()
