# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flVKNoBv6QTeI4HkzFROrgO7NaCOvoZL
"""

from flask import Flask, request, abort
import os
from linebot.v3 import WebhookHandler
from linebot.v3.exceptions import InvalidSignatureError
from linebot.v3.webhooks import MessageEvent, TextMessageContent
from linebot.v3.messaging import (
    Configuration, ApiClient, MessagingApi,
    ReplyMessageRequest,
    TextMessage,
    TemplateMessage,
    ButtonsTemplate,
    URIAction,
)

app = Flask(__name__)

configuration = Configuration(access_token=os.getenv('LINE_Channel_access_token'))
line_handler = WebhookHandler(os.getenv('LINE_Channel_secret'))

@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers['X-Line-Signature']
    body = request.get_data(as_text=True)
    try:
        line_handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    return 'OK'

@line_handler.add(MessageEvent, message=TextMessageContent)
def handle_message(event):
    with ApiClient(configuration) as api_client:
        line_bot_api = MessagingApi(api_client)

        action = event.message.text
        if action == '魔法少女小圓':
          A_template=ButtonsTemplate(
            thumbnail_image_url='https://www.inmediahk.net/files/styles/w775/public/column_images/856137005377_anime-Puella-Magi-Madoka-Magica-the-Movie-Rebellion-DVD-Blu-ray-Hyb-Limited-CD.jpg?itok=71v4ED-u',
            title="魔法少女小圓(2011)",
            text="由日本動畫公司SHAFT製作的原創電視動畫，是唯一同時獲得日本動畫指標性三大獎的動畫，也是最賣座且最重要的作品之一，後有劇場版與外傳",
            actions=[
              URIAction(label="介紹", uri="https://zh.moegirl.org.cn/zh-tw/%E9%AD%94%E6%B3%95%E5%B0%91%E5%A5%B3%E5%B0%8F%E5%9C%86"),
              URIAction(label="網路評價", uri="https://www.stockwich.com/2023/08/18/madoka-magica/"),
              URIAction(label="正版免費觀看管道", uri="https://www.stockwich.com/2023/08/18/madoka-magica/")
            ]
          )
          reply = TemplateMessage(
              alt_text='圖片視窗',
              template=A_template
          )

        else:
          reply = TextMessage(text='請在選單上選擇一個作品')

        line_bot_api.reply_message(
            ReplyMessageRequest(
                reply_token=event.reply_token,
                messages=[
                    reply
                ]
            )
        )


if __name__ == "__main__":
    app.run()
